config/routes.rb
Rails.application.routes.draw do
  root 'wits#index'
  resources :wits

end

app/models/wit.rb
class Wit < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/wits_controller.rb
class WitsController < ApplicationController
  before_action :set_wit, only: [:show, :edit, :update, :destroy]

  # GET /wits
  # GET /wits.json
  def index
    @wits = Wit.all
    @wit = Wit.new
  end

  # GET /wits/1
  # GET /wits/1.json
  def show
  end

  # GET /wits/new
  def new
    @wit = Wit.new
  end

  # GET /wits/1/edit
  def edit
  end

  # POST /wits
  # POST /wits.json
  def create
    @wit = Wit.new(wit_params)

    respond_to do |format|
      if @wit.save
        # format.html { redirect_to @wit, notice: 'Wit was successfully created.' }
        format.json { render json: @wit, status: :created, message: "Yay" }
      else
        format.html { render :new }
        format.json { render json: @wit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wits/1
  # PATCH/PUT /wits/1.json
  def update
    respond_to do |format|
      if @wit.update(wit_params)
        format.html { redirect_to @wit, notice: 'Wit was successfully updated.' }
        format.json { render :show, status: :ok, location: @wit }
      else
        format.html { render :edit }
        format.json { render json: @wit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wits/1
  # DELETE /wits/1.json
  def destroy
    @wit.destroy
    respond_to do |format|
      format.html { redirect_to wits_url, notice: 'Wit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wit
      @wit = Wit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wit_params
      params[:wit].permit(:message, :created_at)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/wits_helper.rb
module WitsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Witterajax</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">

    <div class="row">
      <header class='banner'>
        <h1> <%= link_to "Witter", root_path %></h1>


      </header>
    </div>

    <div class="row">
      <div class="content">
         <%= yield %>
      </div>
    </div>

    <div class="row">
      <footer>
        <p>Made with love</p>
      </footer>
    </div>

</body>
</html>

app/views/wits/_form.html.erb
<%= form_for(@wit) do |f| %>
  <% if @wit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wit.errors.count, "error") %> prohibited this wit from being saved:</h2>

      <ul>
      <% @wit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/wits/edit.html.erb
<h1>Editing Wit</h1>

<%= render 'form' %>

<%= link_to 'Show', @wit %> |
<%= link_to 'Back', wits_path %>

app/views/wits/index.html.erb
<% if flash[:notice] || flash[:alert] %>
    <div class='flash'><%= flash[:notice] || flash[:alert] %></div>
<% end %>

<table class="table table-hover">
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  <thead>
  <tbody>
    <div id='wit-container'>
      <tr>
        <% @wits.each do |wit| %>
          <td><p class="message"> <%= wit.message %> </p></td>
          <td><p class="time"> <%= wit.created_at %></p> <%= link_to 'Destroy', wit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
        <% end %>
    </div>
</table>

<%= form_for(@wit, remote: true, id: 'new-wit') do |f| %>
    <%= f.label :message %>
    <%= f.text_field :message %>
    <%= f.submit %>
<% end %>

app/views/wits/new.html.erb
<h1>New Wit</h1>

<%= render 'form' %>

<%= link_to 'Back', wits_path %>

app/views/wits/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_wit_path(@wit) %> |
<%= link_to 'Back', wits_path %>